version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: hoppscotch
    path: packages/hoppscotch-app/
    text-resources:
      - path: locales/*.json
        format: flat-key-value
